# The main config file for your Jekyll template

# Site settings
title: Han Xiao               # used for the html title of every page
desc: >
  # I am a PhD student in Computer Science at Aalto University.
  # My main research interests are Graph Mining and Machine Learning. 

url: http://xiaohan2012.github.io      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: xiaohan2012@gmail.com
author: Han Xiao
# twitter_username: xiaohan2012
github_username: xiaohan2012
# github_source: jackal

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Research
    url: /research/
  - title: Articles
    url: /articles/
  - title: About me
    url: /about/

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

